function [ output ] = find_angle(data, LorR, joint, axis, FORMAT)
    joint = strcat(LorR,joint);
    Angles          =  {'jL5S1X','jL5S1Y','jL5S1Z'...
                        'jL4L3X','jL4L3Y','jL4L3Z'...
                        'jL1T12X','jL1T12Y','jL1T12Z'...
                        'jT9T8X','jT9T8Y','jT9T8Z'...
                        'jT1C7X','jT1C7Y','jT1C7Z'...
                        'jC1HeadX','jC1HeadY','jC1HeadZ'...
                        'jRightC7ShoulderX','jRightC7ShoulderY','jRightC7ShoulderZ'...
                        'jRightShoulderX','jRightShoulderY','jRightShoulderZ'...
                        'jRightElbowX','jRightElbowY','jRightElbowZ'...
                        'jRightWristX','jRightWristY','jRightWristZ'...
                        'jLeftC7ShoulderX','jLeftC7ShoulderY','jLeftC7ShoulderZ'...
                        'jLeftShoulderX','jLeftShoulderY','jLeftShoulderZ'...
                        'jLeftElbowX','jLeftElbowY','jLeftElbowZ'...
                        'jLeftWristX','jLeftWristY','jLeftWristZ'...
                        'jRightHipX','jRightHipY','jRightHipZ'...
                        'jRightKneeX','jRightKneeY','jRightKneeZ'...
                        'jRightAnkleX','jRightAnkleY','jRightAnkleZ'...
                        'jRightBallFootX','jRightBallFootY','jRightBallFootZ'...
                        'jLeftHipX','jLeftHipY','jLeftHipZ'...
                        'jLeftKneeX','jLeftKneeY','jLeftKneeZ'...
                        'jLeftAnkleX','jLeftAnkleY','jLeftAnkleZ'...
                        'jLeftBallFootX','jLeftBallFootY','jLeftBallFootZ'};

    if isempty(data)
        output='';
    else
        if FORMAT == ".mvnx"
            Length = size(data.subject.frames.frame, 2);
            joint_angle=zeros(1,Length);
            angle=strcat('j',joint,axis);
            N=strfind(Angles,angle);
            n=find(~cellfun(@isempty,N));
            for i=1:Length
                joint_angle(1,i)=data.subject.frames.frame(i).jointAngle(n);
            end
        else
            if axis == "Y" && (joint == "RightElbow" || joint == "LeftElbow")
                joint_angle = '';
            else
                if axis == "Y"
                    joint_angle = data.(joint)(:,3);
                elseif axis == "X"
                    joint_angle = data.(joint)(:,2);
                elseif axis == "Z"
                    joint_angle = data.(joint)(:,1);
                end
            end
        end
        output=joint_angle;
    end
end